### ISSUE TITLE
DNS Error

### ISSUE THREAD

**Issue by AhnMo** [openatx/atx-agent#25]
Hi. 

I got an error with `atx-agent` when I try to test code using `uiautomator2`. 

When I use `app_install` method, the error is :
```
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    d.app_install('http://example.org/AliExpress%20Smarter%20Shopping%20Better%20Living_v6.15.0_apkpure.com.apk')
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 689, in app_install
    return self._wait_install_finished(id, installing_callback)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 744, in _wait_install_finished
    raise RuntimeError("error", jdata.get('error'))
RuntimeError: ('error', u'Get http://example.org/AliExpress%20Smarter%20Shopping%20Better%20Living_v6.15.0_apkpure.com.apk: dial tcp: lookup example.org on [::1]:53: read udp [::1]:42576->[::1]:53: read: connection refused')
```

Is there any solution about this?

I saw the dns server has been fixed at `/dns.go`. Is it related with the error?

**Comment by mingyuan-xia** [comment]
Change `http://example.org/` for a real URL. This is just an example.

**Comment by AhnMo** [comment]
Humm... It's not make sense that it cannot reproduce. Anyway thank you for reply this issue.
