### ISSUE TITLE
在长时间运行之后，会出现自动退出atx-agent现象

### ISSUE THREAD

**Issue by hwangjr** [openatx/atx-agent#35]
长时间运行，抛出错误，查看了下，进程也已经退出，也就是`daemon`没有进行自动重启。

下面是详细日志，我分析了下，感觉都没太大问题，不知道是不是哪里的锁冲突了。

```

10.10.10.166 - - [07/Dec/2018:16:38:52 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
2018/12/07 16:38:52 startservice com.github.uiautomator/.Service
fatal error: schedule: holding locks

runtime stack:
runtime.throw(0x51fe29, 0x17)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:608 +0x5c
runtime.schedule()
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:2561 +0x2f0
runtime.park_m(0x2a808c0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:2676 +0x8c
runtime.mcall(0x28383c0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_arm.s:289 +0x5c

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x98365fc0, 0x72, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x28a6334, 0x72, 0x2919c00, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x7c
internal/poll.(*pollDesc).waitRead(0x28a6334, 0xffffff00, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Accept(0x28a6320, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_unix.go:384 +0x17c
net.(*netFD).accept(0x28a6320, 0x2b06b60, 0x2ae2000, 0x29de0d8)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/fd_unix.go:238 +0x20
net.(*TCPListener).accept(0x280cf20, 0x2ae2040, 0xa319900, 0x4335c)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/tcpsock_posix.go:139 +0x20
net.(*TCPListener).Accept(0x280cf20, 0x2ca0ca4, 0xc, 0x28000e0, 0x29fa00)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/tcpsock.go:260 +0x3c
net/http.(*Server).Serve(0x29d6680, 0x5bfb38, 0x280cf20, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:2826 +0x1e0
main.(*Server).Serve(0x29b2138, 0x5bfb38, 0x280cf20, 0x281aa5d, 0x29b2138)
	/home/travis/gopath/src/github.com/openatx/atx-agent/restapi.go:956 +0x30
main.main()
	/home/travis/gopath/src/github.com/openatx/atx-agent/main.go:608 +0x12e8

goroutine 5 [syscall, 3020 minutes]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/sigqueue.go:139 +0x130
os/signal.loop()
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/signal/signal_unix.go:23 +0x14
created by os/signal.init.0
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/signal/signal_unix.go:29 +0x30

goroutine 14 [syscall, 3020 minutes]:
syscall.Syscall6(0x118, 0x1, 0x374a, 0x2837eb4, 0x1000004, 0x0, 0x0, 0x2801b68, 0x2, 0x3)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/syscall/asm_linux_arm.s:45 +0x8
os.(*Process).blockUntilWaitable(0x28a4240, 0x1, 0x4a5601, 0x18ea8)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/wait_waitid.go:31 +0x64
os.(*Process).wait(0x28a4240, 0x280a998, 0x2837fdc, 0x29a0000)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/exec_unix.go:22 +0x2c
os.(*Process).Wait(0x28a4240, 0x0, 0x2907b40, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/exec.go:125 +0x1c
os/exec.(*Cmd).Wait(0x2884840, 0x3179c4, 0x1)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/exec/exec.go:465 +0x40
os/exec.(*Cmd).Wait-fm(0x2907bc0, 0x2837fdc)
	/home/travis/gopath/src/github.com/openatx/atx-agent/cmdctrl/cmdctrl.go:228 +0x1c
github.com/openatx/atx-agent/cmdctrl.goFunc.func1(0x2907c80, 0x280d110)
	/home/travis/gopath/src/github.com/openatx/atx-agent/cmdctrl/cmdctrl.go:34 +0x1c
created by github.com/openatx/atx-agent/cmdctrl.goFunc
	/home/travis/gopath/src/github.com/openatx/atx-agent/cmdctrl/cmdctrl.go:33 +0x48

goroutine 19 [select, 3020 minutes]:
github.com/openatx/atx-agent/cmdctrl.(*processKeeper).start.func1(0x29d6500)
	/home/travis/gopath/src/github.com/openatx/atx-agent/cmdctrl/cmdctrl.go:229 +0x3cc
created by github.com/openatx/atx-agent/cmdctrl.(*processKeeper).start
	/home/travis/gopath/src/github.com/openatx/atx-agent/cmdctrl/cmdctrl.go:208 +0xd0

goroutine 33 [select]:
github.com/codeskyblue/heartbeat.(*Client).beatLoop(0x2926060, 0x5c0038, 0x29260e0, 0x540be400, 0x2, 0x2ad6030, 0xa, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/codeskyblue/heartbeat@v0.0.0-20180510083815-41c9a36c9169/heartbeat.go:197 +0x124
github.com/codeskyblue/heartbeat.(*Client).Beat.func1(0x2926060, 0x540be400, 0x2, 0x5c0038, 0x29260e0)
	/home/travis/gopath/pkg/mod/github.com/codeskyblue/heartbeat@v0.0.0-20180510083815-41c9a36c9169/heartbeat.go:178 +0x94
created by github.com/codeskyblue/heartbeat.(*Client).Beat
	/home/travis/gopath/pkg/mod/github.com/codeskyblue/heartbeat@v0.0.0-20180510083815-41c9a36c9169/heartbeat.go:159 +0xac

goroutine 21 [syscall]:
syscall.Syscall6(0x118, 0x1, 0x7dc4, 0x2d675ac, 0x1000004, 0x0, 0x0, 0x4f03c0, 0x13b3c, 0x2afcfa8)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/syscall/asm_linux_arm.s:45 +0x8
os.(*Process).blockUntilWaitable(0x29fc150, 0x29fc150, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/wait_waitid.go:31 +0x64
os.(*Process).wait(0x29fc150, 0x1, 0x2afcfa0, 0x2a69840)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/exec_unix.go:22 +0x2c
os.(*Process).Wait(0x29fc150, 0x53b5c8, 0x53b5cc, 0x53b5c4)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/exec.go:125 +0x1c
os/exec.(*Cmd).Wait(0x2c33340, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/exec/exec.go:465 +0x40
os/exec.(*Cmd).Run(0x2c33340, 0x53b8b4, 0x2af90e0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/exec/exec.go:309 +0x44
main.Command.Run(0x2a69820, 0x4, 0x4, 0xb2c97000, 0x8b, 0x1, 0x5bcba8, 0x2ae2060, 0x5bcba8, 0x2ae2060, ...)
	/home/travis/gopath/src/github.com/openatx/atx-agent/utils.go:86 +0x78
main.Command.CombinedOutput(0x2a69820, 0x4, 0x4, 0xb2c97000, 0x8b, 0x1, 0x5bcba8, 0x2ae2060, 0x5bcba8, 0x2ae2060, ...)
	/home/travis/gopath/src/github.com/openatx/atx-agent/utils.go:101 +0x48
main.runShell(0x2a69820, 0x4, 0x4, 0x2afa000, 0x41, 0x600, 0x0, 0x0)
	/home/travis/gopath/src/github.com/openatx/atx-agent/utils.go:117 +0x5c
main.(*Server).initHTTPServer.func17(0x29ac570)
	/home/travis/gopath/src/github.com/openatx/atx-agent/restapi.go:367 +0x48
created by main.(*Server).initHTTPServer
	/home/travis/gopath/src/github.com/openatx/atx-agent/restapi.go:364 +0x698

goroutine 38 [chan receive, 3020 minutes]:
main.main.func3(0x2a8bc40, 0x281aa5d, 0x29b2138)
	/home/travis/gopath/src/github.com/openatx/atx-agent/main.go:587 +0x74
created by main.main
	/home/travis/gopath/src/github.com/openatx/atx-agent/main.go:586 +0x12cc

goroutine 650701 [IO wait]:
internal/poll.runtime_pollWait(0x981f1a00, 0x72, 0xe4938)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x2cb8154, 0x72, 0xffffff01, 0x5be4c8, 0x8f0160)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x7c
internal/poll.(*pollDesc).waitRead(0x2cb8154, 0x2ad2401, 0x200, 0x200)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Read(0x2cb8140, 0x2ad2400, 0x200, 0x200, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_unix.go:169 +0x14c
os.(*File).read(0x2afcf88, 0x2ad2400, 0x200, 0x200, 0x2ad2400, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/file_unix.go:249 +0x3c
os.(*File).Read(0x2afcf88, 0x2ad2400, 0x200, 0x200, 0x98321018, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/file.go:108 +0x4c
bytes.(*Buffer).ReadFrom(0x2ae2060, 0x5bd838, 0x2afcf88, 0x98321018, 0x2ae2060, 0x2a80901, 0x2d747c4)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/bytes/buffer.go:206 +0xa8
io.copyBuffer(0x5bcba8, 0x2ae2060, 0x5bd838, 0x2afcf88, 0x0, 0x0, 0x0, 0x2d747ac, 0x2d747a4, 0x2, ...)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/io/io.go:388 +0x300
io.Copy(0x5bcba8, 0x2ae2060, 0x5bd838, 0x2afcf88, 0x1, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/io/io.go:364 +0x48
os/exec.(*Cmd).writerDescriptor.func1(0x65aec, 0x53b6dc)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/exec/exec.go:279 +0x38
os/exec.(*Cmd).Start.func1(0x2c33340, 0x29ac870)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/exec/exec.go:400 +0x1c
created by os/exec.(*Cmd).Start
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/os/exec/exec.go:399 +0x414

goroutine 650706 [IO wait]:
internal/poll.runtime_pollWait(0x981f1e80, 0x72, 0xe4938)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x2b6c154, 0x72, 0xffffff00, 0x5be4c8, 0x8f0160)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x7c
internal/poll.(*pollDesc).waitRead(0x2b6c154, 0x2982000, 0x1000, 0x1000)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Read(0x2b6c140, 0x2982000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_unix.go:169 +0x14c
net.(*netFD).Read(0x2b6c140, 0x2982000, 0x1000, 0x1000, 0x2c35180, 0x4, 0x141a4)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/fd_unix.go:202 +0x38
net.(*conn).Read(0x29d4088, 0x2982000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/net.go:177 +0x58
net/http.(*persistConn).Read(0x2b88140, 0x2982000, 0x1000, 0x1000, 0x2b1570, 0x2b41a80, 0x2ba3620)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1497 +0x170
bufio.(*Reader).fill(0x29ae120)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/bufio/bufio.go:100 +0x10c
bufio.(*Reader).Peek(0x29ae120, 0x1, 0x0, 0x0, 0x1, 0x2ace140, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/bufio/bufio.go:132 +0x2c
net/http.(*persistConn).readLoop(0x2b88140)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1645 +0x164
created by net/http.(*Transport).dialConn
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1338 +0x7f8

goroutine 619202 [IO wait]:
internal/poll.runtime_pollWait(0x981f1e00, 0x72, 0xe4938)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x28a6424, 0x72, 0xffffff00, 0x5be4c8, 0x8f0160)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x7c
internal/poll.(*pollDesc).waitRead(0x28a6424, 0x2be6000, 0x1000, 0x1000)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Read(0x28a6410, 0x2be6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_unix.go:169 +0x14c
net.(*netFD).Read(0x28a6410, 0x2be6000, 0x1000, 0x1000, 0x291c540, 0x4, 0x141a4)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/fd_unix.go:202 +0x38
net.(*conn).Read(0x2a322e8, 0x2be6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/net.go:177 +0x58
net/http.(*persistConn).Read(0x2b880a0, 0x2be6000, 0x1000, 0x1000, 0x2b1570, 0x2b41180, 0x288de20)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1497 +0x170
bufio.(*Reader).fill(0x2d64330)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/bufio/bufio.go:100 +0x10c
bufio.(*Reader).Peek(0x2d64330, 0x1, 0x0, 0x0, 0x1, 0x2b41780, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/bufio/bufio.go:132 +0x2c
net/http.(*persistConn).readLoop(0x2b880a0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1645 +0x164
created by net/http.(*Transport).dialConn
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1338 +0x7f8

goroutine 650707 [select]:
net/http.(*persistConn).writeLoop(0x2b88140)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1885 +0xb8
created by net/http.(*Transport).dialConn
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1339 +0x814

goroutine 650690 [IO wait]:
internal/poll.runtime_pollWait(0x98365f40, 0x72, 0xe4938)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x2a96834, 0x72, 0xffffff00, 0x5be4c8, 0x8f0160)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x7c
internal/poll.(*pollDesc).waitRead(0x2a96834, 0x2b9c000, 0x1000, 0x1000)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Read(0x2a96820, 0x2b9c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_unix.go:169 +0x14c
net.(*netFD).Read(0x2a96820, 0x2b9c000, 0x1000, 0x1000, 0xffffffff, 0x0, 0x2977e4)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/fd_unix.go:202 +0x38
net.(*conn).Read(0x2afcb90, 0x2b9c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/net.go:177 +0x58
net/http.(*connReader).Read(0x2c5a060, 0x2b9c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:786 +0x14c
bufio.(*Reader).fill(0x29ae000)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/bufio/bufio.go:100 +0x10c
bufio.(*Reader).Peek(0x29ae000, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/bufio/bufio.go:132 +0x2c
net/http.(*conn).readRequest(0x2ae2000, 0x5c0038, 0x2c5a020, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:963 +0xa84
net/http.(*conn).serve(0x2ae2000, 0x5c0038, 0x2c5a020)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:1788 +0x3f0
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:2851 +0x290

goroutine 619203 [select]:
net/http.(*persistConn).writeLoop(0x2b880a0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1885 +0xb8
created by net/http.(*Transport).dialConn
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1339 +0x814
```

**Comment by hwangjr** [comment]
@codeskyblue  或者可以提供一个重启接口（restapi），通过服务端调用，让服务自动平滑重启？

**Comment by codeskyblue** [comment]
版本号

**Comment by hwangjr** [comment]
最新版本也会发生退出现象。 0.5.2。在红米6 上。连续跑一个晚上就挂了，查服务也没有了。
后面解题思路大概是，重新写一个保活程序，通过保活程序，启动 atx-agent，如果服务挂了，就重新启动。发现还有遇到就是，服务存活着，但是端口已经不监听且无法访问了，再进行处理就是如果offline的话，就尝试通过保活服务去重新启动atx-agent，这样达到保活。
目前在用这套策略，还在测试ing。
