### ISSUE TITLE
vivo z3 atx经常会挂掉

### ISSUE THREAD

**Issue by spectop** [openatx/atx-agent#67]
atx-agent version 0.7.2
看上去是 InstrumentationWatcher 出问题了
```
127.0.0.1 - - [08/Jan/2020:20:13:14 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [08/Jan/2020:20:13:15 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 3018
127.0.0.1 - - [08/Jan/2020:20:13:24 +0800] "GET /info HTTP/1.1" 200 660
2020/01/08 20:14:24 reverseproxy.go:442: http: proxy error: context canceled
127.0.0.1 - - [08/Jan/2020:20:13:24 +0800] "POST /jsonrpc/0 HTTP/1.1" 502 0
2020/01/08 20:15:28 reverseproxy.go:442: http: proxy error: context canceled
127.0.0.1 - - [08/Jan/2020:20:14:28 +0800] "POST /jsonrpc/0 HTTP/1.1" 502 0
2020/01/08 20:16:31 reverseproxy.go:442: http: proxy error: context canceled
127.0.0.1 - - [08/Jan/2020:20:15:31 +0800] "POST /jsonrpc/0 HTTP/1.1" 502 0
2020/01/08 20:17:39 httpserver.go:389: startservice com.github.uiautomator/.Service
2020/01/08 20:18:35 reverseproxy.go:442: http: proxy error: context canceled
127.0.0.1 - - [08/Jan/2020:20:17:35 +0800] "POST /jsonrpc/0 HTTP/1.1" 502 0
2020/01/08 20:19:38 reverseproxy.go:442: http: proxy error: context canceled
127.0.0.1 - - [08/Jan/2020:20:18:38 +0800] "POST /jsonrpc/0 HTTP/1.1" 502 0
2020/01/08 20:20:12 reverseproxy.go:442: http: proxy error: read tcp 127.0.0.1:45868->127.0.0.1:9008: read: connection reset by peer
127.0.0.1 - - [08/Jan/2020:20:19:42 +0800] "POST /jsonrpc/0 HTTP/1.1" 502 0
onError: commandError=false message=INSTRUMENTATION_ABORTED: System has crashed.
INSTRUMENTATION_ABORTED: System has crashed.
2020/01/08 20:20:12 cmdctrl.go:27: DEBUG cmd wait err: <nil>
2020/01/08 20:20:12 cmdctrl.go:27: DEBUG idle for 500ms
2020/01/08 20:20:13 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2020/01/08 20:20:13 cmdctrl.go:27: DEBUG program pid: 6674
Error type 2
android.util.AndroidException: Can't connect to activity manager; is the system running?
	at com.android.commands.am.Am.onRun(Am.java:68)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
2020/01/08 20:20:13 cmdctrl.go:27: DEBUG cmd wait err: exit status 1
2020/01/08 20:20:13 cmdctrl.go:27: DEBUG idle for 500ms
2020/01/08 20:21:33 [1;34m[Info] main.go:539 - - - - - - - - - - - - - - -[0m
2020/01/08 20:21:33 [1;34m[Info] main.go:540 daemon started[0m
atx-agent version 0.7.2
Listen on http://192.168.5.3:7912
127.0.0.1 - - [08/Jan/2020:20:21:34 +0800] "GET /version HTTP/1.1" 200 5
127.0.0.1 - - [08/Jan/2020:20:21:34 +0800] "GET /version HTTP/1.1" 200 5
2020/01/08 20:21:34 reverseproxy.go:442: http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
127.0.0.1 - - [08/Jan/2020:20:21:34 +0800] "GET /ping HTTP/1.1" 502 0
127.0.0.1 - - [08/Jan/2020:20:21:34 +0800] "GET /version HTTP/1.1" 200 5
127.0.0.1 - - [08/Jan/2020:20:21:34 +0800] "GET /version HTTP/1.1" 200 5
2020/01/08 20:21:35 reverseproxy.go:442: http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
127.0.0.1 - - [08/Jan/2020:20:21:35 +0800] "GET /ping HTTP/1.1" 502 0
127.0.0.1 - - [08/Jan/2020:20:21:35 +0800] "GET /version HTTP/1.1" 200 5
127.0.0.1 - - [08/Jan/2020:20:21:35 +0800] "GET /info HTTP/1.1" 200 660
2020/01/08 20:21:35 reverseproxy.go:442: http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
127.0.0.1 - - [08/Jan/2020:20:21:35 +0800] "POST /jsonrpc/0 HTTP/1.1" 502 0
127.0.0.1 - - [08/Jan/2020:20:21:38 +0800] "POST /shell HTTP/1.1" 200 45
2020/01/08 20:21:38 [1;34m[Info] main.go:584 service uiautomator: startservice com.github.uiautomator/.Service
[0m127.0.0.1 - - [08/Jan/2020:20:21:38 +0800] "POST /uiautomator HTTP/1.1" 200 20
2020/01/08 20:21:38 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2020/01/08 20:21:38 cmdctrl.go:27: DEBUG program pid: 6244
127.0.0.1 - - [08/Jan/2020:20:21:38 +0800] "GET /uiautomator HTTP/1.1" 200 16
2020/01/08 20:21:38 reverseproxy.go:442: http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
127.0.0.1 - - [08/Jan/2020:20:21:38 +0800] "GET /ping HTTP/1.1" 502 0
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.github.uiautomator.stub.Stub:
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: 1
127.0.0.1 - - [08/Jan/2020:20:21:39 +0800] "GET /uiautomator HTTP/1.1" 200 16
```

**Comment by XDSwang** [comment]
建议开启自启动权限，不需要就请关闭
